tests:
  script:
    - pip3 install -r requirements.txt
    - export PONTUS_DATABASE="${POSTGRES_NAME}"
    - export PONTUS_USER="postgres"
    - export PONTUS_PASSWORD=""
    - export PONTUS_HOST="${POSTGRES_PORT_5432_TCP_ADDR}"
    - export PONTUS_PORT="5432"
    - py.test app/tests/unit --cov=app
  services:
    - postgres:9.4.4
  tags:
    - docker

complexity:
  script:
    - xenon --max-average A --max-modules B --max-absolute B .
  tags:
    - docker

flake8:
  script:
    - flake8 *
  tags:
    - docker

deploy_dev:
  stage: deploy
  environment: dev
  script:
    - docker build -t hellobink/metis:dev .
    - docker login -u binkautomation -p epitome-generic-basilisk
    - docker push hellobink/metis:dev
  only:
    - master
  tags:
    - shell

deploy_staging:
  stage: deploy
  environment: staging
  script:
    - docker build -t hellobink/metis:staging .
    - docker login -u binkautomation -p epitome-generic-basilisk
    - docker push hellobink/metis:staging
  only:
    - staging
  tags:
    - shell

deploy_production:
  stage: deploy
  environment: production
  script:
    - docker build -t hellobink/metis:production .
    - docker login -u binkautomation -p epitome-generic-basilisk
    - docker push hellobink/metis:production
  only:
    - production
  tags:
    - shell
