tests:
  script:
    - pip3 install -r requirements.txt
    - export PONTUS_DATABASE="${POSTGRES_NAME}"
    - export PONTUS_USER="postgres"
    - export PONTUS_PASSWORD=""
    - export PONTUS_HOST="${POSTGRES_PORT_5432_TCP_ADDR}"
    - export PONTUS_PORT="5432"
    - py.test app/tests/unit --cov=app
  services:
    - postgres:9.4.4
  tags:
    - docker

complexity:
  script:
    - xenon --max-average A --max-modules B --max-absolute B .
  tags:
    - docker

flake8:
  script:
    - flake8 *
  tags:
    - docker

deploy:
  image: hellobink/ansible
  stage: deploy
  environment: dev
  script:
    - cd /ansible && ansible-playbook playbooks/deploy/flask.yml -e project=metis -e hosts=dev_web
  only:
    - master
  tags:
    - docker
