stages:
  - tests
  - build
  - deploy

tests:
  stage: tests
  script:
    - pip3 install -r requirements.txt
    - export PONTUS_DATABASE="${POSTGRES_NAME}"
    - export PONTUS_USER="postgres"
    - export PONTUS_PASSWORD=""
    - export PONTUS_HOST="${POSTGRES_PORT_5432_TCP_ADDR}"
    - export PONTUS_PORT="5432"
    - py.test app/tests/unit --cov=app
  services:
    - postgres:9.4.4

complexity:
  stage: tests
  script:
    - xenon --max-average A --max-modules B --max-absolute B .

flake8:
  stage: tests
  script:
    - flake8 *

build-develop:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build --pull -t "$CI_REGISTRY/metis:latest" .
    - docker push "$CI_REGISTRY/metis:latest"
  only:
    - develop

build-master:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build --pull -t "$CI_REGISTRY/metis:$CI_COMMIT_TAG" .
    - docker push "$CI_REGISTRY/metis:$CI_COMMIT_TAG"
  only:
    - tags

deploy-dev:
  stage: deploy
  image: binkops.azurecr.io/kubedeployer:latest
  environment: dev
  script:
    - kubectl config use-context dev
    - kubectl delete po $(kubectl get po --no-headers=true pods -l run=metis -o custom-columns=:metadata.name)
  only:
    - develop

deploy-staging:
  stage: deploy
  image: binkops.azurecr.io/kubedeployer:latest
  environment: staging
  script:
    - kubectl config use-context staging
    - kubectl set image deployment/metis:$CI_COMMIT_TAG
  only:
    - tags

deploy-prod:
  stage: deploy
  image: binkops.azurecr.io/kubedeployer:latest
  environment: prod
  script:
    - kubectl config use-context prod
    - kubectl set image deployment/metis:$CI_COMMIT_TAG
  when: manual
  only:
    - tags

