stages:
  - tests
  - build
  - tagging
  - prod

tests:
  stage: tests
  image: olympus.azurecr.io/python:3.6
  script:
    - mkdir -p /root/.ssh
    - echo $DEPLOY_KEY | base64 -d > /root/.ssh/id_rsa
    - chmod 600 /root/.ssh/id_rsa
    - ssh-keyscan git.bink.com > /root/.ssh/known_hosts
    - pipenv install --system --deploy --dev --ignore-pipfile
    - export PONTUS_DATABASE="${POSTGRES_NAME}"
    - export PONTUS_USER="postgres"
    - export PONTUS_PASSWORD=""
    - export PONTUS_HOST="${POSTGRES_PORT_5432_TCP_ADDR}"
    - export PONTUS_PORT="5432"
    - pytest app/tests/unit --cov=app
  services:
    - postgres:9.4.4

complexity:
  stage: tests
  image: olympus.azurecr.io/python:3.6
  script:
    - xenon --max-average A --max-modules B --max-absolute B .

flake8:
  stage: tests
  image: olympus.azurecr.io/python:3.6
  script:
    - flake8

build-develop:
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build --pull -t "$CI_REGISTRY/metis:latest" .
    - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock "$CI_REGISTRY/aqua-scanner:5.0" scan --local "$CI_REGISTRY/metis:latest" --host https://aqua.uksouth.bink.sh:30001/ --user scanner --password $AQUA_PASSWORD --show-negligible --policies Bink --text
    - docker push "$CI_REGISTRY/metis:latest"
  only:
    - develop

tag-develop:
  stage: tagging
  image: binkops.azurecr.io/tagbot:latest
  environment: dev
  script:
    - tagbot --username "$CI_REGISTRY_USER" --password "$CI_REGISTRY_PASSWORD" --source "$CI_REGISTRY/metis:latest" --tag "develop-$CI_COMMIT_SHORT_SHA"
  only:
    - develop

build-master:
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build --pull -t "$CI_REGISTRY/metis:$CI_COMMIT_TAG" .
    - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock "$CI_REGISTRY/aqua-scanner:5.0" scan --local "$CI_REGISTRY/metis:$CI_COMMIT_TAG" --host https://aqua.uksouth.bink.sh:30001/ --user scanner --password $AQUA_PASSWORD --show-negligible --policies Bink --text
    - docker push "$CI_REGISTRY/metis:$CI_COMMIT_TAG"
  only:
    - tags

tag-staging:
  stage: tagging
  image: binkops.azurecr.io/tagbot:latest
  environment: staging
  script:
    - tagbot --username "$CI_REGISTRY_USER" --password "$CI_REGISTRY_PASSWORD" --source "$CI_REGISTRY/metis:$CI_COMMIT_TAG" --tag "staging-$CI_COMMIT_TAG"
  only:
    - tags

tag-preprod:
  stage: tagging
  image: binkops.azurecr.io/tagbot:latest
  environment: prod
  script:
    - tagbot --username "$CI_REGISTRY_USER" --password "$CI_REGISTRY_PASSWORD" --source "$CI_REGISTRY/metis:$CI_COMMIT_TAG" --tag "preprod-$CI_COMMIT_TAG"
  when: manual
  only:
    - tags

tag-prod:
  stage: prod
  image: binkops.azurecr.io/tagbot:latest
  environment: prod
  script:
    - tagbot --username "$CI_REGISTRY_USER" --password "$CI_REGISTRY_PASSWORD" --source "$CI_REGISTRY/metis:$CI_COMMIT_TAG" --tag "prod-$CI_COMMIT_TAG"
  when: manual
  only:
    - tags
