tests:
  script:
    - pip3 install -r requirements.txt
    - export PONTUS_DATABASE="${POSTGRES_NAME}"
    - export PONTUS_USER="postgres"
    - export PONTUS_PASSWORD=""
    - export PONTUS_HOST="${POSTGRES_PORT_5432_TCP_ADDR}"
    - export PONTUS_PORT="5432"
    - py.test app/tests/unit --cov=app
  services:
    - postgres:9.4.4
  tags:
    - docker

complexity:
  script:
    - xenon --max-average A --max-modules B --max-absolute B .
  tags:
    - docker

flake8:
  script:
    - flake8 *
  tags:
    - docker

deploy:
  stage: deploy
  script:
    - docker build -t registry.gitlab.com/hellobink/olympus/metis/image:build-$CI_PIPELINE_ID -t registry.gitlab.com/hellobink/olympus/metis/image:latest .
    - docker login registry.gitlab.com -u binkautomation -p $REPO_PASS
    - docker push registry.gitlab.com/hellobink/olympus/metis/image:latest
    - docker push registry.gitlab.com/hellobink/olympus/metis/image:build-$CI_PIPELINE_ID
    - docker rmi registry.gitlab.com/hellobink/olympus/metis/image:latest
    - docker rmi registry.gitlab.com/hellobink/olympus/metis/image:build-$CI_PIPELINE_ID
  only:
    - master
  tags:
    - shell


