stages:
  - tests
  - dev
  - staging
  - preprod
  - prod

tests:
  stage: tests
  image: binkhq/python:3.9
  variables:
    POSTGRES_HOST_AUTH_METHOD: trust
    PONTUS_DATABASE: postgres
    PONTUS_USER: postgres
    PONTUS_PASSWORD: ""
    PONTUS_HOST: postgres
    PONTUS_PORT: "5432"
  before_script:
    - pip install pipenv
    - pipenv install --system --deploy --dev --ignore-pipfile
  script:
    - pytest app/tests/unit --cov=app
  services:
    - postgres:11

complexity:
  stage: tests
  image: binkhq/python:3.9
  before_script:
    - pip install xenon
  script:
    - xenon --max-average A --max-modules B --max-absolute B .

flake8:
  stage: tests
  image: binkhq/python:3.9
  before_script:
    - pip install flake8
  script:
    - flake8

dev:
  stage: dev
  environment: 
    name: dev
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - export CTAG="develop-$(date +%F-%H%M%S)"
    - docker build --pull -t "$CI_REGISTRY/metis:$CTAG" .
    - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock "$CI_REGISTRY/aqua-scanner:5.0" scan --local "$CI_REGISTRY/metis:$CTAG" --host https://aqua.uksouth.bink.sh:30001/ --user scanner --password $AQUA_PASSWORD --show-negligible --policies Bink --text
    - docker push "$CI_REGISTRY/metis:$CTAG"
  only:
    - develop

staging:
  stage: staging
  environment:  
    name: staging
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - export CTAG="staging-$(date +%F-%H%M%S)"
    - docker build --pull -t "$CI_REGISTRY/metis:$CTAG" .
    - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock "$CI_REGISTRY/aqua-scanner:5.0" scan --local "$CI_REGISTRY/metis:$CTAG" --host https://aqua.uksouth.bink.sh:30001/ --user scanner --password $AQUA_PASSWORD --show-negligible --policies Bink --text
    - docker push "$CI_REGISTRY/metis:$CTAG"
  only:
    - staging

preprod:
  stage: preprod
  environment:  
    name: preprod
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - export CTAG="preprod-$(date +%F-%H%M%S)"
    - docker build --pull -t "$CI_REGISTRY/metis:$CTAG" .
    - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock "$CI_REGISTRY/aqua-scanner:5.0" scan --local "$CI_REGISTRY/metis:$CTAG" --host https://aqua.uksouth.bink.sh:30001/ --user scanner --password $AQUA_PASSWORD --show-negligible --policies Bink --text
    - docker push "$CI_REGISTRY/metis:$CTAG"
  when: manual
  only:
    - master

prod:
  stage: prod
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - export CTAG="prod-$CI_COMMIT_TAG"
    - docker build --pull -t "$CI_REGISTRY/metis:$CTAG" .
    - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock "$CI_REGISTRY/aqua-scanner:5.0" scan --local "$CI_REGISTRY/metis:$CTAG" --host https://aqua.uksouth.bink.sh:30001/ --user scanner --password $AQUA_PASSWORD --show-negligible --policies Bink --text
    - docker push "$CI_REGISTRY/metis:$CTAG"
  when: manual
  only:
    - tags
