tests:
  script:
    - pip3 install -r requirements.txt
    - export PONTUS_DATABASE="${POSTGRES_NAME}"
    - export PONTUS_USER="postgres"
    - export PONTUS_PASSWORD=""
    - export PONTUS_HOST="${POSTGRES_PORT_5432_TCP_ADDR}"
    - export PONTUS_PORT="5432"
    - py.test app/tests/unit --cov=app
  services:
    - postgres:9.4.4
  tags:
    - docker

complexity:
  script:
    - xenon --max-average A --max-modules B --max-absolute B .
  tags:
    - docker

flake8:
  script:
    - flake8 *
  tags:
    - docker

deploy-dev:
  stage: deploy
  script:
    - docker build -t olympus.azurecr.io/metis:latest .
    - docker login olympus.azurecr.io -u $AZURE_LOGIN -p $AZURE_PASS
    - docker push olympus.azurecr.io/metis:latest
    - docker rmi olympus.azurecr.io/metis:latest
    - docker logout olympus.azurecr.io
  environment: dev
  only:
    - master
  tags:
    - shell

deploy-staging:
  stage: deploy
  script:
    - docker build -t olympus.azurecr.io/metis:staging .
    - docker login olympus.azurecr.io -u $AZURE_LOGIN -p $AZURE_PASS
    - docker push olympus.azurecr.io/metis:staging
    - docker rmi olympus.azurecr.io/metis:staging
    - docker logout olympus.azurecr.io
  environment: staging
  only:
    - staging
  tags:
    - shell

deploy-production:
  stage: deploy
  script:
    - docker build -t olympus.azurecr.io/metis:production .
    - docker login olympus.azurecr.io -u $AZURE_LOGIN -p $AZURE_PASS
    - docker push olympus.azurecr.io/metis:production
    - docker rmi olympus.azurecr.io/metis:production
    - docker logout olympus.azurecr.io
  environment: production
  only:
    - production
  tags:
    - shell
