import settings
import json
import time
import hmac
import hashlib
import base64
import requests
from datetime import datetime

'''E2: https://api.qa.americanexpress.com/v2/datapartnership/offers/sync
E3: https://apigateway.americanexpress.com/v2/datapartnership/offers/sync'''
'''Amex use sync to add cards and unsync to remove cards from transactions output'''

testing_receiver_token = 'BqfFb1WnOwpbzH7WVTqmvYtffPV'
testing_create_url = 'https://api.qa.americanexpress.com/v2/datapartnership/offers/sync'
testing_remove_url = 'https://api.qa.americanexpress.com/v2/datapartnership/offers/unsync'
production_receiver_token = ''
production_create_url = 'https://apigateway.americanexpress.com/v2/datapartnership/offers/sync'
client_id = "e0e1114e-b63d-4e72-882b-29ad364573ac"
client_secret = "a44bfb98-239c-4ac0-85ae-685ed110e3af"


class Amex:
    def url(self):
        if not settings.TESTING:
            service_url = production_create_url
        else:
            service_url = testing_create_url
        return service_url

    def receiver_token(self):
        if not settings.TESTING:
            receiver_token = production_receiver_token
        else:
            receiver_token = testing_receiver_token
        return receiver_token

    def request_header(self):
        header_start = '![CDATA['
        content_type = 'Content-Type: x-www-form-urlencoded'
        auth_header = mac_auth_header()

        authentication = 'Authentication: {}'.format(auth_header)
        api_key = 'X-AMEX-API-KEY: {}'.format(client_id)
        oauth_resp = self.amex_oauth(auth_header)
        access_token = oauth_resp
        access_key = 'X-AMEX-ACCESS-KEY: ' + access_token
        header_end = ']]'

        header = "{0} {1} {2} {3} {4} {5} {6}".format(header_start, content_type,
                                                      authentication, api_key, access_token, access_key, header_end)
        return header

    def request_body(self):
        msgId = time.mktime(datetime.now().timetuple())  # 'Can this be a guid or similar?'
        partnerId = 'Amex to provide'
        cmAlias1 = 'card_id_token'
        distrChan = 'Amex to provide'

        data = {
            "msgId": msgId,
            "partnerId": partnerId,
            "cardNbr": "{{credit_card_number}}",
            "cmAlias1": cmAlias1,
            "distrChan": distrChan
        }
        # Todo - check if "langCd": "en", "ctryCd": "US", required

        body_data = '![CDATA[{' + json.dumps(data) + '}]]'
        return body_data

    def amex_oauth(self, auth_header):
        # Call the Amex OAuth endpoint to obtain an API request token.
        base_url = "https://api.qa.americanexpress.com"
        auth_url = base_url + "/apiplatform/v2/oauth/token/mac"
        # payload = "grant_type=client_credentials&app_spec_info=Apigee&guid_type=privateguid&scope=ThanxSmartOffers_"
        payload = "grant_type=client_credentials&scope="

        header = {"Content-Type": "application/x-www-form-urlencoded",
                  "Authentication": auth_header,
                  "X-AMEX-API-KEY": client_id}

        resp = requests.post(auth_url, data=payload, headers=header)
        resp_json = json.loads(resp.content.decode())
        if resp.status_code == 200:
            return resp_json["access_token"]
        else:
            return None


def mac_auth_header():
    """
    Authentication=”MAC id=” client id value”,
    ts=”time stamp generated by client(In unix epoch time format)”,
    nonce=”unique identifier string”,
    mac=”request MAC generated using HMAC SHA1 algorithm”
    i. Use HMAC SHA1 algorithm.
    ii. Base string constructed using below parameters with following order followed by newline
        a.  client_id
        b. ts (timestamp in unix epoch format)
        c. nonce
        d. grant_type
    iii. Use client_secret as key.
    iv. Base 64 encoding on output raw data
    :return: mac token.
    """
    secret_key = client_secret.encode('utf-8')

    ts = str(int(time.time()))
    nonce = ts + ":AMEX"
    base_string = client_id + "\n" + ts + "\n" + nonce + "\n" + "client_credentials" + "\n"
    base_string_bytes = base_string.encode('utf-8')

    dig = hmac.new(secret_key, msg=base_string_bytes, digestmod=hashlib.sha256).digest()
    mac = str(base64.b64encode(dig), 'utf-8')

    auth_header = "MAC id=\"" + client_id + "\",ts=\"" + ts + "\",nonce=\"" + nonce + "\",mac=\"" + mac + "\""
    print(auth_header.replace('"', r'\"'))
    return auth_header
